### ISSUE TITLE
Execution failed for task ':webResourceCompileLess'

### ISSUE THREAD

**Issue by willis7** [ksoichiro/gradle-web-resource-plugin#1]
build.gradle

```
plugins {
    id "com.github.ksoichiro.web.resource" version "1.0.5"
}

webResource {
    base {
          // Change base directories for src/dest
          src = '.'
          dest = '.'
    }
    coffeeScript.enabled = false
    less {
        // Set false if you don't use LESS related features
        enabled = true
        // Change LESS src/dest directories and filter setting
        src = 'less'
        dest = 'css'
        // Default: true
        minify = false
    }
}
```

⇒  gradle --version

```
------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.11 x86_64
```

Stacktrace:

```
⇒  gradle webResourceCompile --s
:webResourceSetupNodeDependencies UP-TO-DATE
:webResourceInstallBowerDependencies UP-TO-DATE
:webResourceCompileCoffeeScript UP-TO-DATE
:webResourceCompileLess FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webResourceCompileLess'.
> java.lang.reflect.UndeclaredThrowableException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':webResourceCompileLess'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
    at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:155)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:152)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:100)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:94)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:94)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
    at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    at org.gradle.util.Swapper.swap(Swapper.java:38)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.reflect.UndeclaredThrowableException
    at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:504)
    at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
    at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
    at jsr166y.ForkJoinPool.invoke(ForkJoinPool.java:1492)
    at groovyx.gpars.extra166y.ParallelArrayWithMapping.apply(ParallelArrayWithMapping.java:48)
    at groovyx.gpars.extra166y.ParallelArray.apply(ParallelArray.java:329)
    at groovyx.gpars.pa.GParsPoolUtilHelper.eachParallelPA(GParsPoolUtilHelper.groovy:192)
    at groovyx.gpars.GParsPoolUtil.eachParallel(GParsPoolUtil.java:383)
    at groovyx.gpars.TransparentParallel.invokeMethod(TransparentParallel.groovy)
    at groovyx.gpars.TransparentParallel.each(TransparentParallel.groovy:36)
    at com.github.ksoichiro.web.resource.task.WebResourceCompileLessTask$_exec_closure4_closure5.doCall(WebResourceCompileLessTask.groovy:41)
    at groovyx.gpars.GParsPoolUtil.asConcurrent(GParsPoolUtil.java:324)
    at com.github.ksoichiro.web.resource.task.WebResourceCompileLessTask$_exec_closure4.doCall(WebResourceCompileLessTask.groovy:40)
    at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy:174)
    at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy)
    at groovyx.gpars.GParsPool.withExistingPool(GParsPool.groovy:173)
    at groovyx.gpars.GParsPool$withExistingPool$1.callStatic(Unknown Source)
    at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:145)
    at groovyx.gpars.GParsPool$withPool$0.callStatic(Unknown Source)
    at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:121)
    at groovyx.gpars.GParsPool$withPool.call(Unknown Source)
    at com.github.ksoichiro.web.resource.task.WebResourceCompileLessTask.exec(WebResourceCompileLessTask.groovy:39)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 68 more
Caused by: java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy46.op(Unknown Source)
    at groovyx.gpars.extra166y.AbstractParallelAnyArray$OUPap.leafApply(AbstractParallelAnyArray.java:640)
    at groovyx.gpars.extra166y.PAS$FJOApply.atLeaf(PAS.java:147)
    at groovyx.gpars.extra166y.PAS$FJBase.internalCompute(PAS.java:118)
    at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:106)
    at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
    at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
    at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
    at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
    at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
    at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
Caused by: java.util.concurrent.ExecutionException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "css" from undefined (/Users/sionix/Code/byte-shifter-web/build/webResource/less.js#25)
    at io.apigee.trireme.core.ScriptFuture.getResult(ScriptFuture.java:82)
    at io.apigee.trireme.core.ScriptFuture.get(ScriptFuture.java:97)
    at io.apigee.trireme.core.ScriptFuture.get(ScriptFuture.java:36)
    at java_util_concurrent_Future$get.call(Unknown Source)
    at com.github.ksoichiro.web.resource.node.TriremeNodeRunner.exec(TriremeNodeRunner.groovy:20)
    at com.github.ksoichiro.web.resource.node.TriremeNodeRunner$exec.call(Unknown Source)
    at com.github.ksoichiro.web.resource.task.WebResourceCompileLessTask$_exec_closure4_closure5_closure6.doCall(WebResourceCompileLessTask.groovy:60)
    at groovyx.gpars.pa.GParsPoolUtilHelper$_eachParallelPA_closure8.doCall(GParsPoolUtilHelper.groovy:192)
    ... 11 more
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "css" from undefined (/Users/sionix/Code/byte-shifter-web/build/webResource/less.js#25)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
    at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962)
    at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981)
    at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3993)
    at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1505)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_less_js_4565._c_anonymous_3(/Users/sionix/Code/byte-shifter-web/build/webResource/less.js:25)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_less_js_4565.call(/Users/sionix/Code/byte-shifter-web/build/webResource/less.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_render_js_5293._c_anonymous_6(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/render.js:33)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_render_js_5293.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/render.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_parse_js_5299._c_anonymous_6(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/parse.js:63)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_parse_js_5299.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/parse.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_parser_parser_js_5148._c_anonymous_9(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/parser/parser.js:183)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_parser_parser_js_5148.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/parser/parser.js)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_visitors_import_visitor_js_5114._c_anonymous_4(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/visitors/import-visitor.js:35)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_visitors_import_visitor_js_5114.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/visitors/import-visitor.js)
    at org.mozilla.javascript.BoundFunction.call(BoundFunction.java:53)
    at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_visitors_import_sequencer_js_5118._c_anonymous_6(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/visitors/import-sequencer.js:50)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_visitors_import_sequencer_js_5118.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/visitors/import-sequencer.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_visitors_import_visitor_js_5114._c_anonymous_3(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/visitors/import-visitor.js:29)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_visitors_import_visitor_js_5114.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/visitors/import-visitor.js)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_parser_parser_js_5148._c_anonymous_7(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/parser/parser.js:188)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_parser_parser_js_5148.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/parser/parser.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_parse_js_5299._c_anonymous_3(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/parse.js:60)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_parse_js_5299.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/parse.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_render_js_5293._c_anonymous_3(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/render.js:25)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_node_modules_less_lib_less_render_js_5293.call(/Users/sionix/Code/byte-shifter-web/build/webResource/node_modules/less/lib/less/render.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_less_js_4565._c_lessConvert_2(/Users/sionix/Code/byte-shifter-web/build/webResource/less.js:17)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_less_js_4565.call(/Users/sionix/Code/byte-shifter-web/build/webResource/less.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_less_js_4565._c_anonymous_1(/Users/sionix/Code/byte-shifter-web/build/webResource/less.js:13)
    at org.mozilla.javascript.gen._Users_sionix_Code_byte_shifter_web_build_webResource_less_js_4565.call(/Users/sionix/Code/byte-shifter-web/build/webResource/less.js)
    at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2586)
    at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:287)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
    at io.apigee.trireme.node12.node.module._c_anonymous_16(module.js:460)
    at io.apigee.trireme.node12.node.module.call(module.js)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
    at io.apigee.trireme.node12.node.module._c_anonymous_22(module.js:478)
    at io.apigee.trireme.node12.node.module.call(module.js)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
    at io.apigee.trireme.node12.node.module._c_anonymous_14(module.js:355)
    at io.apigee.trireme.node12.node.module.call(module.js)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
    at io.apigee.trireme.node12.node.module._c_anonymous_12(module.js:310)
    at io.apigee.trireme.node12.node.module.call(module.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
    at io.apigee.trireme.node12.node.module._c_anonymous_24(module.js:501)
    at io.apigee.trireme.node12.node.module.call(module.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
    at io.apigee.trireme.node12.main.trireme._c_startup_2(trireme.js:143)
    at io.apigee.trireme.node12.main.trireme.call(trireme.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
    at io.apigee.trireme.node12.main.trireme._c_anonymous_1(trireme.js:748)
    at io.apigee.trireme.node12.main.trireme.call(trireme.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
    at io.apigee.trireme.node12.main.trireme.call(trireme.js)
    at io.apigee.trireme.core.internal.ScriptRunner.runScript(ScriptRunner.java:762)
    at io.apigee.trireme.core.internal.ScriptRunner$4.run(ScriptRunner.java:702)
    at org.mozilla.javascript.Context.call(Context.java:501)
    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:503)
    at io.apigee.trireme.core.internal.ScriptRunner.call(ScriptRunner.java:697)
    at io.apigee.trireme.core.ScriptFuture.run(ScriptFuture.java:183)


BUILD FAILED

Total time: 10.859 secs
```

**Comment by willis7** [comment]
Despite the error, I can see a css directory with compiled css inside but I have no way of testing if everything is there. This is the Bootstrap Less code.

**Comment by ksoichiro** [comment]
Thank you for reporting this!
I confirmed the issue.
I'll look into it later.

**Comment by ksoichiro** [comment]
@willis7 
In this case, `bootstrap/less/**/*.less` should be excluded (should not be compiled), but `bootstrap/less/bootstrap.less` should be included.
(bootstrap.less imports other files)
But we can't specify this pattern with the current version.

To handle this, I added a new configuration option `filters` to 1.1.0-SNAPSHOT.
Could you try this version?
This is a snapshot, so you can use it with this dependency setting:

``` gradle
//plugins {
//    id "com.github.ksoichiro.web.resource" version "1.0.5"
//}
buildscript {
    repositories {
        jcenter()
        maven {
            url uri('https://oss.sonatype.org/content/repositories/snapshots/')
        }
    }
    dependencies {
        classpath 'com.github.ksoichiro:gradle-web-resource-plugin:1.1.0-SNAPSHOT'
    }
}

apply plugin: 'com.github.ksoichiro.web.resource'
```

And the configuration will be like this:

``` gradle
webResource {
    ...
    less {
        ...
        // Add this 'filters' to include bootstrap.less
        filters {
            exclude '**/bootstrap/less/**/*.less'
            include '**/bootstrap/less/bootstrap.less'
        }
    }
    ...
}
```

Then only `bootstrap/less/bootstrap.less` will be compiled.

**Comment by willis7** [comment]
I had a play with this also and found the following worked:

```
plugins {
    id "com.github.ksoichiro.web.resource" version "1.0.5"
}

webResource {
    base {
          // Change base directories for src/dest
          src = '.'
          dest = '.'
    }
    coffeeScript.enabled = false
    less {
        // Set false if you don't use LESS related features
        enabled = true
        // Change LESS src/dest directories and filter setting
        src = 'less'
        dest = 'css'

        filters.include 'bootstrap.less'

        // Default: true
        minify = false
    }
}
```

**Comment by ksoichiro** [comment]
Thank you for checking!

**Comment by willis7** [comment]
No problem, great plugin :+1:
